#!/bin/sh

screen python src/run_model.py CNN+LSTM reg_consolidated aug_consolidated \
--train \
--test \
--output_dir run_history/lrcn_second_run \
--epochs 150 \
--batch_size 4 \
--width_shift_range 0.25 \
--height_shift_range 0.25 \
--zoom_range 0.25 \
--shear_range 25 \
--rotation_range 25 \
--horizontal_flip \
--vertical_flip
