#!/bin/sh

python src/run_model.py CNN+LSTM rsz \
--train \
--test \
--partition_csv subject_data.csv \
--output_dir run_history/test_new_method \
--epochs 2 \
--batch_size 4 \
--width_shift_range 0.25 \
--height_shift_range 0.25 \
--zoom_range 0.25 \
--shear_range 25 \
--rotation_range 25 \
--horizontal_flip \
--vertical_flip
