#!/bin/sh

#<<<<<<< HEAD
#screen python src/run_model.py CNN+LSTM rsz \
#--train \
#--test \
#--partition_csv subject_data.csv \
#--output_dir run_history/lrcn_4_color \
#--epochs 50 \
#=======
# --zoom_range 0.10 \
# --shear_range 0 \
#--width_shift_range 0.10 \
#--height_shift_range 0.10 \
#--rotation_range 25 \
#--cyclic_learning_rate 0.00001 0.00009 \
#--horizontal_flip \
#--vertical_flip \

pip install --upgrade src/we_panic_utils/
python src/run_model.py 3D-CNN rsz32 \
--train \
--test \
--partition_csv subject_data.csv \
--output_dir run_history/CNN_3D_32x32 \
--input_dir run_history/CNN_3D_32x32 \
--epochs 100 \
--steps_per_epoch 1 \
--batch_size 12 \
--greyscale_on \
--normalize \
