#!/bin/bash

python src/scripts/augment_speed.py data DeepLearningClassData.csv NextStartingPoint.csv && \
python src/scripts/extract_frames.py NextStartingPoint.csv DeepLearningClassData.csv data frames && \
python src/scripts/resize_trials.py frames
